WITH CUSTOMERORDERS AS (
    SELECT C.CUSTOMERID, CONCAT(C.FIRSTNAME, ' ', C.LASTNAME) AS CUSTOMERNAME, COUNT(O.ORDERID) AS NUMBEROFORDERS
    FROM L1_LANDING.CUSTOMERS C
    JOIN L1_LANDING.ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
    GROUP BY C.CUSTOMERID, CUSTOMERNAME
    ORDER BY NUMBEROFORDERS DESC
)

SELECT CUSTOMERID, CUSTOMERNAME, NUMBEROFORDERS
FROM CUSTOMERORDERS